# Generated by Django 3.1.3 on 2020-11-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvintefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palestras.ouvinte')),
                ('palestrafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palestras.palestra')),
            ],
        ),
    ]
