# Generated by Django 3.1.4 on 2020-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0002_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='datetitmeEnd',
            field=models.DateTimeField(),
        ),
    ]
